project:
  type: website
  output-dir: _render

execute:
  freeze: auto
  echo: true

website:
  favicon: "slides/figures/OUCRU.jpg"
  site-url: https://oucru-modelling.github.io/R-training-2026/
  navbar:
    logo: slides/figures/OUCRU.jpg
    left:
      - href: index.qmd
        text: Home
      - href: handouts/precourse_setup.qmd
        text: Pre-course setups
      - href: slides/IntroductionRDay1.qmd
        text: Introduction to R (Day 1)
      - href: slides/viz.qmd
        text: Principles of data visualisation
      - href: slides/qt-repro-res.qmd
        text: Reproducible research and reporting using Quarto
    tools:
      - icon: github
        href: https://github.com/OUCRU-Modelling/R-training-2026
        text: Quarto GitHub
format:
  html:
    respect-user-color-scheme: true
    toc: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
  


