project:
  type: website
  output-dir: _render

execute:
  freeze: auto
  echo: true

website:
  title: "R-training-2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/viz.qmd
        text: Principles of data visualisation

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



