---
title: "OUCRU R training course - 2026"
format: 
  html:
    link-external-icon: true
    link-external-newwindow: true
from: markdown+autolink_bare_uris
number-depth: 2
toc-depth: 2
date: last-modified
date-format: "MMMM D, YYYY -- HH:mm:ss (z)"
---

# Housekeeping

- The training will be **09:00 – 17:00 (UTC +7)** for everyday
- There will be a **lunch break between 12:30 – 13:30 (UTC +7)**
- Lunch will be provided for in-person attendees who filled in their attendance on
  [ferendum.com]{style="text-decoration: underline;"}. If you did not, you need to arrange lunch yourself. 

## Contributors

- Prof. Ronald Geskus, Biostatistics group, OUCRU HCM
- Mr. Thinh Ong Phuc, Mathematical Modeling group, OUCRU HCM
- Mr. Tuyen Huynh, Mathematical Modeling group, OUCRU HCM
- Dr. Tran Thai Hung, Biostatistics group, OUCRU HCM
- Ms. Anh Phan Truong Quynh, Mathematical Modeling group, OUCRU HCM
- Dr. Duc Du Hong, Biostatistics group, OUCRU HCM
- Dr. Thuan Hoang Van, Biostatistics group, OUCRU Ha Noi
- Dr. Nguyen Lam Vuong, Biostatistics group, OUCRU HCM
- Mr. Nguyen Pham Nguyen The, Mathematical Modeling group, OUCRU HCM

## Pre-course setups and requirements

Please follow this [pre-course setups handout](handouts/precourse_setup.qmd) to setup R and RStudio.

# Course topics

## Introduction to R

### Day 1 (Monday)

- [Lecture slides](slides/IntroductionRDay1.qmd){.external target="_blank"}
- **Learning objectives**:
  1. Basic structure of R
  2. Simple computations
  3. Import and inspect datasets
  4. Make selections
  5. Navigate RStudio with confidence

- Exercises:
  - [Exercises](handouts/exercises_Day1.qmd){.external target="_blank"}
  - [Exercise answers](handouts/exercises_Day1_answer.qmd){.external target="_blank"}
  - {{< downloadthis handouts/exercises_Day1_answer.R dname="exercises_Day1_answer" label="Exercise answers script" type="primary">}}
- {{< downloadthis slides/Scripts/ExampleCodeDay1.R dname="ExampleCodeDay1" label="Example R code scripts - Day 1" type="primary">}}

### Day 2 (Tuesday)

- [Lecture slides](slides/IntroductionRDay2.qmd){.external target="_blank"}
- **Learning objectives**:
  1. Create visualisations using Base R graphics
  2. Write simple functions to automate tasks; the package system
  3. Lists
  4. Using *pipe operators* to chain functions
- R code:
  - {{< downloadthis handouts/exercises_Day2_answer.R dname="exercises_Day2_answer" label="Exercise answers script" type="primary">}}
- {{< downloadthis slides/Scripts/ExampleCodeDay2.R dname="ExampleCodeDay2"
  label="Example R code scripts - Day 2" type="primary">}}


## Principles of data visualisation and plotting in R

### Day 3 (Wednesday):

- [Lecture slides](slides/viz.qmd)
- **Learning objectives**:
  1. The grammar of graphics—understanding how plots are built
  2. The step-by-step process of creating graphs in R
  3. Use the `ggplot2` package plot figures in R
  4. How to design clear and impactful visualisations
  5. Using LLMs (Large Language Models) to help you with plotting
  
- [Exercises](handouts/exercises_Day3.qmd){.external target="_blank"}

- R code:
  - {{< downloadthis handouts/exercises_Day3_answer.R dname="exercises_Day3_answer" label="Exercise answers script" type="primary">}}


### Day 4 (Thursday-morning):

- [Lecture slides](slides/VisualisationSlides.pdf)
- **Learning objectives**:
  1. Understand the principles of clear and impactful visualisation

- [Handout file](handouts/VisualisationHandouts.pdf)
- Exercises:
  - [Exercise answer key](handouts/Exercises_Day4a_answer.pdf)
  - [Exercise answer script](handouts/Exercises_Day4a_answer.R)
  - Datasets: 
    - [Data Nightingale Rose (csv file)](slides/data/NightingaleRose.csv)
    - [Data ICU cost (csv file)](slides/data/ICUCost.csv)

## Advance data management and techniques in R

### Day 4 (Thursday-afternoon):

- [Lecture slides](slides/advance-R.qmd)
- **Learning objectives**:
  1. Into the `tidyverse`
  2. Logics with if-else statements and for-loops
  3. Data manipulation with `tidyverse`
      - Data ingestion with `readr`
      - Pivotting dataframes with `tidyr`
      - Column manipulation with `dplyr`
  4. Joining dataframes
  5. Vectors and vectorisation in R



## Reproducible research and reporting using Quarto

### Day 5 (Friday-morning)

- [Lecture slides](slides/qt-repro-res.qmd)
- **Learning objectives**:
  1. Write papers with reproducible tables and figures using Quarto
  2. Generate reports in multiple formats: Word, PDF, slides, web pages…
  3. Easily update analyses when new data becomes available

- In class example: [my_project.zip](handouts/my_project.zip){target="_blank"}
- [Exercises](handouts/exercises_Day5.qmd){target="_blank"}

# Appendix

## Introduction to R and RStudio

Good introduction, with explanatory videos:

- RStudio provides several tutorials for beginners and more advanced users: https://education.rstudio.com/
- Datacamp provides many courses at different levels (OUCRU HCMC has a license). See http://www.statmethods.net. The [introduction](https://www.datacamp.com/courses/free-introduction-to-r) is free
- A basic course, interactive design: https://www.quantargo.com/courses/course-r-introduction
- Introduction from Pasteur institute: https://hub-courses.pages.pasteur.fr/R_pasteur_phd/First_steps_RStudio.html
- Good summary of basic concepts: http://www.burns-stat.com/documents/tutorials/impatient-r
- A comprehensive introduction: https://github.com/matloff/fasteR
- Introduction to R programming: https://jjallaire.github.io/hopr/


## DeepeR into R

- The book [R for Data Science (2e)](https://r4ds.hadley.nz/)
- ["What They Forgot to Teach You About R"](https://rstats.wtf/index.html)
- https://www.r-project.org/doc/bib/R-books.html
- The official R manuals: https://cran.r-project.org/manuals.html

## R and statistics

- A simple introduction to biomedical statistics using R: https://a-little-book-of-r-for-biomedical-statistics.readthedocs.io/en/latest/
- A website with detailed examples of all types of statistical analysis: https://stats.oarc.ucla.edu/other/dae/
- R by example: http://www.mayin.org/ajayshah/KB/R/index.html 
- [R course, with focus machine learning](https://www.udemy.com/course/data-science-and-machine-learning-bootcamp-with-r/)

## R Markdown and Quarto

- The main RStudio webpage on R Markdown, with links to two freely available books: https://rmarkdown.rstudio.com/docs/
- [Introduction](https://rmarkdown.rstudio.com/lesson-1.html) from RStudio
- [Introduction to `knitr`](https://sachsmc.github.io/knit-git-markr-guide/knitr/knit.html)
- [First steps in Markdown](https://www.r-bloggers.com/2022/02/how-to-use-r-markdown-part-one/)
- Writing academic papers with R Markdown (focus on bibiliographies): https://ikashnitsky.github.io/2019/zotero/
- R Markdown tips: https://appsilon.com/r-markdown-tips/
- Powerpoint presentations using R Markdown: https://appsilon.com/r-markdown-powerpoint-presentation/
- https://codingclubuc3m.rbind.io/post/2019-09-24/ focus on creating presentations
- R Quarto tutorial: https://appsilon.com/r-quarto-tutorial/
