---
title: "Pre-course setups and requirements"
author: 
    - "Ronald Geskus"
    - "Tuyen Huynh"
number-sections: true
format: 
  html:
    link-external-newwindow: true
    link-external-icon: true
navbar: true
date: last-modified
date-format: "MMMM D, YYYY -- HH:mm:ss (z)"
---

# About {.unnumbered}

Here we explain how to install R and RStudio on your own computer. This is **required** to ensure a smooth experience and reproducible results during the course.


# R

1. Go to the [R website](http://www.r-project.org)
2. In the column on the left hand side, click on the [CRAN](https://cran.r-project.org/mirrors.html) link under the subheading **Download**
    - You now see a page with *CRAN Mirrors*. This is a list of servers from which the R software and extensions can be downloaded from
3. Click on the first link
    - Now both the left hand side and the right hand side of the page change (This page can be saved as a bookmark/favorite)
4. On the right hand side, click on the download link for your operating system
    - E.g. Windows users click on [Download R for Windows](https://cloud.r-project.org/), then click on **base** and download the program from there.
    - It is recommended to install the latest version as well as to upgrade the program if a new major version is released, which is about once per year
    - You can use the default installation options


# RStudio Desktop

1. Go to [the download page](https://posit.co/download/rstudio-desktop/)
2. Scroll down, look for **2: Install Rstudio** and click on the button for downloading **RStudio Desktop**
3. Download and install RStudio Desktop
    - You can use the default installation options
4. Open Rstudio Desktop, to check that everything has been installed correctly
    - E.g. via the **Start** menu in Windows

# `renv` setup

> The [`renv`](https://rstudio.github.io/renv/) package helps you create reproducible environments for your R projects. Use `renv` to make your R projects more **isolated**, portable and **reproducible**.

For better error reproducilibity, environment consistency, and ease of debugging, we will setup an `renv` environment for the course. Follow these steps:

1. In your normal R console, install `renv` with 

```r
install.packages("renv")
```

2. Initialise `renv` in the project environment with 

```r
renv::init()
```

::: {.callout-note collapse="true"}

Make sure you're in the correct working directory!

You can check from the R console with `getwd()` and set the correct working directory with `setwd(...)`

:::

3. Restart your R session


::: {.callout-tip collapse="true"}

This can be done using Ctrl+Shift+F10 on Windows and Cmd+Shift+F10 on MacOS

:::

4. Check your R console upon restart. It should say that `renv` is loaded and activated!



(This will be quickly walked through again on the first session of the course)